<a href="https://colab.research.google.com/github/Sreenavya04/B19_1244-PDS-/blob/main/22_08_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
#.writing to a file
fp=open("example.txt","w")
fp.write("hello,B.tech students!\n")
fp.write("this is the file handling in python.\n")
fp.write("sr university")
fp.write(" navya")
fp.close()
print("Data written successfully!")

Data written successfully!


In [58]:
# Reading from a file
file=open("example.txt","r")
content=file.read()
print("File content:\n",content)
file.close()

File content:
 hello,B.tech students!
this is the file handling in python.
sr university navya


In [59]:
# read line by line
file=open("example.txt","r")
line1=file.readline()
print("first line:",line1)
line2=file.readline()
print("second line:",line2)
line3=file.readline()
print("third line:",line3)
file.close()

first line: hello,B.tech students!

second line: this is the file handling in python.

third line: sr university navya


In [60]:
#6.Reading all lines into the list
file=open("example.txt","r")
lines=file.readlines()
print("All lines as list:\n",lines)
file.close()

All lines as list:
 ['hello,B.tech students!\n', 'this is the file handling in python.\n', 'sr university navya']


In [61]:
# appending data to an existing file
file=open("example.txt","a")
file.write("\n Appending new data...")
file.close()

In [62]:
with open("example.txt","r") as file:
    content=file.read()
    print(content)

hello,B.tech students!
this is the file handling in python.
sr university navya
 Appending new data...


In [63]:
import csv
with open("data.csv","w",newline='')as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","Age","course"],["Vaishu",21,"cse"],["Karats",20,"cse"],["Navs",19,"cse"],["Soups",20,"ece"]])

In [64]:
#reading from csv
with open("data.csv","r")as file:
  rd=csv.reader(file)
  for row in rd:
    print(row)

['Name', 'Age', 'course']
['Vaishu', '21', 'cse']
['Karats', '20', 'cse']
['Navs', '19', 'cse']
['Soups', '20', 'ece']


In [65]:
import numpy as np
#1D ARRAY
arr1=np.array([1,2,3,4])
print("1D Array:",arr1)
#2D ARRAY
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",arr2)
#ZEROS ARRAY
zeros_arr=np.zeros((3,3))
print("Zeros Array:\n",zeros_arr)
#ONES ARRAY
ones_arr=np.ones((2,4))
print("Ones Array:\n",ones_arr)
#RANGE OF NUMBERS
range_arr=np.arange(0,10,2)
print("Range Array:",range_arr)
#RANDOM ARRAY
rand_arr=np.random.rand(2,3)
print("Random Array:\n",rand_arr)


1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Range Array: [0 2 4 6 8]
Random Array:
 [[0.33565135 0.89442191 0.2927916 ]
 [0.61740723 0.47957893 0.88371064]]


In [66]:
#Attributes
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("Shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Datatype:",arr.dtype)
print("Size:",arr.size)
print("Item size:",arr.itemsize)

Shape: (2, 4)
Dimension: 2
Datatype: int64
Size: 8
Item size: 8


In [67]:
arr=np.array([10,20,30,40,50])
print("First element:",arr[0])
print("Last element:",arr[-1])
print("Slice [1:4]:",arr[1:4])
print("Every second element:",arr[::2])
#2D indexing
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Element at (1,2):",arr2d[0,1])
print("Second row:",arr2d[1,:])
print("Second column:",arr2d[:,1])

First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Every second element: [10 30 50]
Element at (1,2): 2
Second row: [4 5 6]
Second column: [2 5 8]


In [68]:
#Array operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("power:",a**2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
power: [1 4 9]


In [69]:
#mathematical functions
arr=np.array([0,np.pi/2,np.pi,4*np.pi/3])
print("Sin values:",np.sin(arr))
print("Cos values:",np.cos(arr))
print("square root:",np.sqrt(arr))

Sin values: [ 0.00000000e+00  1.00000000e+00  1.22464680e-16 -8.66025404e-01]
Cos values: [ 1.000000e+00  6.123234e-17 -1.000000e+00 -5.000000e-01]
square root: [0.         1.25331414 1.77245385 2.04665342]


In [70]:
#Aggregate functions
arr=np.array([[1,2,3],[4,5,6]])
print("sum:",np.sum(arr))
print("max:",np.max(arr))
print("min:",np.min(arr))
print("mean:",np.mean(arr))
print("standard deviation:",np.std(arr))
print("sum along axis 0:",np.sum(arr,axis=0))
print("sum along axis 1:",np.sum(arr,axis=1))

sum: 21
max: 6
min: 1
mean: 3.5
standard deviation: 1.707825127659933
sum along axis 0: [5 7 9]
sum along axis 1: [ 6 15]


In [71]:
#Broadcasting
a=np.array([1,2,3])
b=5
print("add scalar to array:",a+b)
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print("Broadcasted sum:\n",c+d)

add scalar to array: [6 7 8]
Broadcasted sum:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [72]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix Multiplicatiion:\n",np.dot(A,B))
print("Transpose:\n",A.T)
print("Inverse:\n",np.linalg.inv(A))
print("Determinant:",np.linalg.det(A))

Matrix Multiplicatiion:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004


In [73]:
import numpy as np

# Marks of students in 3 subjects
marks = np.array([
    [85, 90, 88],
    [78, 81, 85],
    [92, 89, 95]
])

print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
